# Generated by Django 4.0.3 on 2022-03-18 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_profile_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='slug',
            field=models.SlugField(default='', editable=False, max_length=200),
        ),
        migrations.AddField(
            model_name='skill',
            name='slug',
            field=models.SlugField(default='', editable=False, max_length=200),
        ),
    ]
