# Generated by Django 4.0.3 on 2022-03-18 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_profile_slug_alter_skill_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='slug',
            field=models.SlugField(default='', editable=False, max_length=200),
        ),
        migrations.AlterField(
            model_name='skill',
            name='slug',
            field=models.SlugField(default='', editable=False, max_length=200),
        ),
    ]
