# Generated by Django 4.0.3 on 2022-03-22 19:30

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_profile_collaborators'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='slug',
        ),
        migrations.AlterField(
            model_name='profile',
            name='social_github',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='social_linkedin',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='social_twitter',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='social_website',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='social_youtube',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.CreateModel(
            name='Social',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('github', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('twitter', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('linkedin', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('youtube', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('website', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.profile')),
            ],
        ),
    ]
