# Generated by Django 4.0.3 on 2022-03-23 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_remove_skill_slug_alter_profile_social_github_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='social',
            name='facebook',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='social',
            name='google',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='social',
            name='stackoverflow',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
