# Generated by Django 4.0.3 on 2022-03-24 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_profile_collaborators_collaborator'),
    ]

    operations = [
        migrations.RenameField(
            model_name='social',
            old_name='facebook',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='collaborators',
        ),
        migrations.RemoveField(
            model_name='social',
            name='github',
        ),
        migrations.RemoveField(
            model_name='social',
            name='google',
        ),
        migrations.RemoveField(
            model_name='social',
            name='linkedin',
        ),
        migrations.RemoveField(
            model_name='social',
            name='stackoverflow',
        ),
        migrations.RemoveField(
            model_name='social',
            name='twitter',
        ),
        migrations.RemoveField(
            model_name='social',
            name='website',
        ),
        migrations.RemoveField(
            model_name='social',
            name='youtube',
        ),
        migrations.AddField(
            model_name='social',
            name='url',
            field=models.URLField(blank=True, default='', max_length=300, null=True),
        ),
        migrations.DeleteModel(
            name='Collaborator',
        ),
    ]
