# Generated by Django 4.0.3 on 2022-03-24 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_rename_facebook_social_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='social',
            name='name',
            field=models.CharField(blank=True, choices=[('github', 'Github'), ('twitter', 'Twitter'), ('facebook', 'Facebook'), ('linkedin', 'LinkedIn'), ('youtube', 'YouTube'), ('google', 'Google'), ('stackoverflow', 'StackOverFlow'), ('website', 'Website')], default='', max_length=200, null=True),
        ),
    ]
