# Generated by Django 4.0.3 on 2022-03-24 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_alter_social_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='social',
            name='name',
            field=models.CharField(blank=True, choices=[('github', 'Github'), ('linkedin', 'LinkedIn'), ('stackoverflow', 'stackoverflow'), ('twitter', 'twitter'), ('youtube', 'youtube'), ('google', 'google'), ('facebook', 'facebook'), ('website', 'website')], default='', max_length=200, null=True),
        ),
    ]
