# Generated by Django 4.0.3 on 2022-03-24 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_alter_social_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='social',
            name='css',
            field=models.CharField(blank=True, default='im im-globe', editable=False, max_length=50, null=True),
        ),
    ]
