# Generated by Django 4.0.3 on 2022-03-24 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_alter_social_css'),
    ]

    operations = [
        migrations.AlterField(
            model_name='social',
            name='name',
            field=models.CharField(blank=True, default='github', max_length=200, null=True),
        ),
    ]
