# Generated by Django 4.0.3 on 2022-03-24 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_alter_social_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='social',
            options={'ordering': ['account', 'name']},
        ),
    ]
