# Generated by Django 4.0.3 on 2022-04-11 17:51

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_remove_profile_social_github_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Opportunity',
            fields=[
                ('poster', models.CharField(blank=True, max_length=200, null=True)),
                ('title', models.CharField(max_length=200, null=True)),
                ('body', models.TextField(max_length=200, null=True)),
                ('weblink', models.URLField(blank=True, default='', max_length=300, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owner', to='users.profile')),
                ('read', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='read', to='users.profile')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
