# Generated by Django 4.0.3 on 2022-04-11 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_opportunity'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='company',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='slug',
            field=models.SlugField(default='', editable=False, max_length=200),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='body',
            field=models.TextField(max_length=5000, null=True),
        ),
    ]
