# Generated by Django 4.0.3 on 2022-04-11 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_opportunity_company_opportunity_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opportunity',
            name='slug',
            field=models.SlugField(default='', max_length=200),
        ),
        migrations.AlterUniqueTogether(
            name='opportunity',
            unique_together={('poster', 'title')},
        ),
    ]
