# Generated by Django 4.0.3 on 2022-04-15 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_alter_profile_slug'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='opportunity',
            unique_together={('company', 'title')},
        ),
    ]
