# Generated by Django 4.0.5 on 2022-06-29 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0029_alter_opportunity_body_alter_opportunity_weblink_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='social',
            name='url',
            field=models.URLField(default='', max_length=300),
        ),
    ]
