# Generated by Django 4.0.5 on 2022-06-29 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0030_alter_social_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='social',
            name='name',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
