# Generated by Django 4.0.3 on 2022-03-26 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_alter_social_options'),
        ('projects', '0012_alter_project_slug'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='project',
            unique_together={('slug', 'owner')},
        ),
    ]
