# Generated by Django 4.0.3 on 2022-04-15 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0013_alter_project_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='demo',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
