# Generated by Django 4.0.4 on 2022-06-14 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0015_project_app_name_project_project_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_directory',
            field=models.CharField(blank=True, default=models.CharField(blank=True, default='', max_length=200, null=True), max_length=200, null=True),
        ),
    ]
