# Generated by Django 4.0.4 on 2022-06-14 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0016_project_project_directory'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='app_directory',
            field=models.CharField(blank=True, default=models.CharField(blank=True, default='', max_length=200, null=True), max_length=200, null=True),
        ),
    ]
