# Generated by Django 4.0.4 on 2022-06-15 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0017_project_app_directory'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='demo_set',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
