# Generated by Django 4.0.4 on 2022-06-16 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0019_project_site_directory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='app_directory',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_directory',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='site_directory',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
