# Generated by Django 4.0.5 on 2022-06-27 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('projects', '0020_alter_project_app_directory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='site',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='sites.site'),
        ),
    ]
