# Generated by Django 4.0.5 on 2022-06-29 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0021_project_site'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='site',
        ),
    ]
