# Generated by Django 4.0.3 on 2022-03-10 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_profile_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='alumn',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='enrolled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='graduation_date_month',
            field=models.DateField(default=3),
        ),
        migrations.AddField(
            model_name='profile',
            name='graduation_date_year',
            field=models.DateField(default=2022),
        ),
    ]
