# Generated by Django 4.0.3 on 2022-03-10 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_profile_alumn_profile_enrolled_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='graduation_date_month',
            field=models.DateField(default='3'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='graduation_date_year',
            field=models.DateField(default='2022'),
        ),
    ]
